APPSCHOOL1-REPO/finalproject-gitspace

GitSpace/Sources/Router/ContentView.swift, GitSpace/Sources/ViewModels/GitHubAuthManager.swift, GitSpace/Sources/ViewModels/MessageViewModel.swift, GitSpace/Sources/ViewModels/RepositoryViewModel.swift, GitSpace/Sources/ViewModels/TagViewModel.swift, GitSpace/Sources/ViewModels/UserViewModel.swift, GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift, GitSpace/Utilities/Constant.swift
- #277
- closed
```swift
static let COLLECTION_USER_INFO: String = "UserInfo"
static let FIELD_GITHUB_ID: String = "githubID"
static let FIELD_DEVICE_TOKEN: String = "deviceToken"
static let FIELD_BLOCKED_USER_IDS: String = "blockedUserIDs"
db
.collection(const.COLLECTION_USER_INFO)
.document(user.id)
.updateData([const.FIELD_BLOCKED_USER_IDS : newBlockedUserIDs])
```
=> [Fix] Firestore DB UserInfo와 관련된 컬렉션과 필드명을 리터럴 값에서 Utility의 전역 상수로 교체합니다.

GitSpace/InitialView.swift, GitSpace/Sources/ViewModels/GitHubAuthManager.swift, GitSpace/Sources/Views/Auth/SigninView.swift
- #281 자동로그인과 관련하여 로티 로딩 뷰가 안뜨는 문제 해결 및 기타 코드 수정
- 로그인 시 실제 로그인 진행중에만 로딩뷰가 뜰 수 있도록 GitHubAuthManager의 signin() 내에서 credential이 nil이 아닐때만 self.state를 pending으로 바꿔주었습니다.
- InitialView.swift에서 signin state가 .pending일 때 LoadingProgressView를 띄우도록 하였습니다. 이로 인해 로그인 웹뷰에서 중도에 웹뷰를 나가거나 혹은 웹뷰가 뜨기 전 로딩뷰가 계속 뜨는 문제를 해결하였습니다.
- 자동로그인 로직 실행 시 signin()메소드를 타지 않아 state가 .pending으로 바뀌지 않기에 로딩뷰가 안뜨는 문제가 발생하였습니다. 이를 GitHubAuthManager 내의 reauthenticateUser() 메소드 시작 시 state를 pending으로 변경하여 로딩뷰가 뜰 수 있도록 코드를 수정하여 문제를 해결하였습니다.
=> #281 sign in view auto login loading yeseul

GitSpace/Sources/Views/Home/ContributorListCell.swift, GitSpace/Sources/Views/Home/ContributorListView.swift
ContributorListView에서 유저 사진, 이름 등을 클릭할 때는 해당 유저의 프로필로 이동할 수 있도록 구현하였습니다.
- GitSpace User의 경우 SendKnockView로 연결되는 것의 우선순위가 높다고 판단되어, 유저 사진을 눌렀을 경우에만 해당 유저의 프로필로 이동할 수 있도록 구현하였습니다.
- Non-GitSpace User의 경우 유저 사진, 이름을 클릭할 때 해당 유저의 프로필로 이동할 수 있도록 구현하였습니다.
- Contributors가 여러명이고, CurrentUser만 GitSpaceUser일 경우 Description이 잘못 표시되는 이슈가 있었습니다.
- 조건문의 ` gitSpaceUserList.count == 1 `를 ` contributorManager.contributors.count == 1 `로 변경하여 버그를 픽스하였습니다.
=> Feat/#291 ContirbutorListView-MoveToProfile-hanho

GitSpace/Sources/Views/Chat/MainChat/ChatListSection.swift
- #289 
- 채팅방 갯수를 확인하여 fetch가 끝난 후 채팅방의 갯수가 0일 때 empty view를 띄워주도록 하였습니다.
=> [Chore] #289 채팅 갯수가 0개일 때 ChatListSection에 empty view를 띄워주도록 코드 추가.

GitSpace/Sources/ViewModels/ContributorViewModel.swift, GitSpace/Sources/Views/Home/ContributorListView.swift, GitSpace/Sources/Views/Home/RepositoryDetailView.swift
- Contributors가 불러와지는 동안(.isLoading) ContributorListView에 진입할 경우, View가 깨지는 현상을 수정했습니다.
- ` .disabled(contributorViewModel.isLoading) ` 코드를 추가 했습니다.
- 오타를 수정했습니다.
- ` devideUser ` -> ` divideUser `
```diff
GSNavigationLink(style: .primary) {
ContributorListView(service: GitHubService(), repository: repository, contributorManager: contributorViewModel)
.navigationTitle("Contributors")
} label: {
GSText.CustomTextView(style: .title3, string:"✊🏻  Knock Knock!")
}
+    .disabled(contributorViewModel.isLoading)
```
=> [Fix] #299 Contributors가 불러와지는 동안(.isLoading) ContributorListView에 진입할 경우, View가 깨지는 현상을 수정했습니다.

GitSpace/InitialView.swift
- current user가 삭제되지 않아 발생하는 zombie user 문제를 해결했습니다. (정공법 아님)
- #301 
- UserDefault에 AT도 있는지 확인하여 로그인 상태 조건을 추가함
```diff
.onViewDidLoad {
if githubAuthManager.authentification.currentUser != nil 
+      && UserDefaults.standard.string(forKey: "AT") != nil 
{
Task {
await githubAuthManager.reauthenticateUser()
githubAuthManager.state = .signedIn
}
}
}
```
=> [Fix] #301 zombie user 문제를 해결했습니다. (임시방편)

GitSpace/Sources/Views/Knock/SendKnockView.swift
1. ~` View Profile ` NavigationLink를 해당 유저의 프로필로 이동할 수 있도록 연결합니다.~
- UserProfileView 작업이 완료되면 연결 할 예정입니다.
2. 구현하지 못한 기능들과 최초 릴리즈 버전에 필요하지 않은 코드들을 주석 처리 또는 삭제했습니다.
- TextEditor 섹션의 사진 / 코드 첨부 버튼 주석처리
- `Offer` / `Question` 버튼 다크모드 대응
- TextEditor 섹션의 키보드 숨기기 버튼 삭제
3. 노크 메세지를 보내고 난 후, 노크 메세지에 대한 Description들이 보이지 않게 수정하였습니다.
- TextEditor와 Send 버튼의 경우, 기존의 뷰에서 Send 버튼에 변동이 있을 경우 (위치가 조정되거나 사라질 때)
` Publishing changes from within view updates is not allowed, this will cause undefined behavior. `
위의 에러가 발생하는 문제가 있어 추후 작업을 통해 TextEditor와 Send 버튼도 보이지 않게 수정할 예정입니다.
현재, 노크 메세지를 보내고 난 후에는 Send 버튼은 작동하지 않습니다. 
- TextEditor 섹션의 사진 / 코드 첨부 버튼 주석 처리
- `Offer` / `Question` 버튼 다크모드 대응
- TextEditor 섹션의 키보드 숨기기 버튼 삭제
- 노크 메세지를 보내고 난 후, 노크 메세지에 대한 Description들이 보이지 않게 분기 처리
=> [Feat / Chore] #303 SendKnockView | 최초 릴리즈 버전에 맞게 뷰를 수정했습니다.

GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift
- #308 
- ChatRoomView에서 ChatRoomInfoView로 연결하는 네비게이션 툴바 링크 제거
- 메세지 입력 필드 좌측 이미지 첨부 / 레포지토리 첨부 버튼 제거
=> [Chore] 출시 버전에 맞춰서 사용하지 않은 Chat View의 컴포넌트들을 숨김 처리 했습니다.

GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift, GitSpace/Sources/Views/Knock/SendKnockView.swift, GitSpace/Utilities/Components/GSTextEditor.swift
- #310 
- 공백 / 개행문자만 존재하는 케이스를 검사하는 정규식 패턴 구현
- GSTextEditor 디자인 시스템으로 문자열 검사 로직 위치 변경
- 메세지 전송 버튼을 디자인 시스템 내부로 이동
```swift
// MARK: SendButton 관련 프로퍼티
let sendableImage: String
let unSendableImage: String
let action: () -> Void
---
private var isMessageSendable: Bool {
let messageText = text.wrappedValue
guard messageText.isEmpty == false else { return false }
let pattern: String = "^[ \n]*$"
if messageText.range(of: pattern,
options: .regularExpression) != nil {
return false
}
return true
}
```
=> [Feat] GSTextEditor 디자인 시스템에 메세지 전송 가능 유효성 검사 체크 로직을 추가했습니다.

GitSpace/Sources/ViewModels/TagViewModel.swift, GitSpace/Sources/Views/Home/AddTagSheetView.swift, GitSpace/Sources/Views/Home/RepositoryDetailView.swift, GitSpace/Sources/Views/Home/StarredView.swift
- #259 작업 중 Tagging에서 삭제 기능이 없다는 것을 확인했다.
- 그래서 RepositoryDetailView에서 AddTagSheetView로 진입했을 때, Tag 삭제가 되도록 로직을 추가하였다.
- deleteRepositoryTag(_:)
- AddTagSheetView에서 진입한 뷰에 따라서 Done을 눌렀을 때 로직이 달라지도록 구현
```swift
func selectTag(to tag: Tag) {
if selectedTags.contains(tag) {
let selectedIndex: Int = selectedTags.firstIndex(of: tag)!
deselectedTags.append(tag)
guard let selectedIndex: Int = selectedTags.firstIndex(of: tag) else {
return
}
selectedTags.remove(at: selectedIndex)
} else {
selectedTags.append(tag)
guard let deselectedIndex: Int = deselectedTags.firstIndex(of: tag) else {
return
}
deselectedTags.remove(at: deselectedIndex)
}
}
```
=> [Add] #259 Tagging에서 삭제 기능을 추가했습니다.

GitSpace/Sources/ViewModels/TagViewModel.swift, GitSpace/Utilities/Constant.swift
- 특정 레포에서 Tagging이 안되는 Bug(#333)를 분석하다보니 다른 사용자들의 Tag가 공유되어서 생긴 문제임을 확인하였습니다.
- 원인은 Repository의 Tag를 불러오는 메서드 `requestRepositoryTags(_:)`에서 collectionGroup의 사용이었습니다.
- collectionGroup을 제거하고 일반 collection으로 변경
- UserInfo에서 Tag에 접근하도록 수정
- 오류 구문 컨벤션에 맞게 수정
- Const 적용
```diff
let snapshot = try await database
-   .collectionGroup(const.COLLECTION_TAG)
+   .collection(const.COLLECTION_USER_INFO)
+   .document(Auth.auth().currentUser?.uid ?? "")
+   .collection(const.COLLECTION_TAG)
.whereField(const.FIELD_REPOSITORIES, arrayContains: "\(repositoryName)")
.getDocuments()
```
=> [Fix] #333 다른 사용자들의 Tag가 공유되는 Bug를 수정하였습니다.

GitSpace.xcodeproj/project.pbxproj, GitSpace/GitSpaceApp.swift, GitSpace/Sources/Network/APIModels/FollowingResponse.swift, GitSpace/Sources/Network/Endpoints/GitHubAPIEndpoint.swift, GitSpace/Sources/Network/Services/GitHubService.swift, GitSpace/Sources/ViewModels/FollowerViewModel.swift, GitSpace/Sources/Views/Chat/MainChat/ChatUserRecommendationSection.swift, GitSpace/Sources/Views/Chat/MainChat/MainChatView.swift, GitSpace/Sources/Views/Profile/CurrentUserProfileView.swift, GitSpace/Sources/Views/Profile/FollowingSkeletonView.swift, GitSpace/Sources/Views/Profile/TargetUserFollowingListView.swift, GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
- TargetUser의 Following과 Followers List를 호출하는 함수를 구현하고 적용합니다.
- GitHubAPIEndpoint에 case를 추가하였습니다.
- `case userFollowingList(userName: String, perPage: Int, page: Int)`
- `case userFollowerList(userName: String, perPage: Int, page: Int)`
- GitHubServiceProtocol에 함수를 추가하였습니다.
```swift
/// 특정 유저의 Following List를 요청하는 함수
func requestUserFollowingList(userName: String, perPage: Int, page: Int) async -> Result<[FollowingResponse], GitHubAPIError>
/// 특정 유저의 Follower List를 요청하는 함수
func requestUserFollowerList(userName: String, perPage: Int, page: Int) async -> Result<[FollowingResponse], GitHubAPIError>
```
- GitHubService에 함수를 구현하였습니다.
```swift
func requestUserFollowingList(userName: String, perPage: Int, page: Int) async -> Result<[FollowingResponse], GitHubAPIError> {
return await …
```
=> [Feat] #327 TargetUser의 Following과 Followers List를 호출하는 함수를 구현하고 적용합니다.

.gitignore, GitSpace/Resources/App/plist/GoogleService-Info.plist, GitSpace/Resources/App/plist/Info.plist, GitSpace/Sources/ViewModels/GitHubAuthManager.swift, GitSpace/Sources/ViewModels/UserViewModel.swift
- #357 
- GithubAuthManager의 signIn 메서드 로직을 비동기로 전환
- registerNewUser에 await 키워드를 추가하여, UserInfo가 DB에 정상적으로 추가된 후 ContentView로 전환되도록 수정
=> [HotFix] 신규 유저정보 등록 시 deviceToken 필드가 정상적으로 반영되지 않는 문제를 해결했습니다.

GitSpace/Sources/Models/Report.swift, GitSpace/Sources/Views/Common/BlockView.swift, GitSpace/Sources/Views/Common/ReportView.swift, GitSpace/Sources/Views/Common/SuggestBlockView.swift, GitSpace/Sources/Views/Profile/TargetUserProfileView.swift, GitSpace/Utilities/CustomHostingController.swift, GitSpace/Utilities/Extensions/View+.swift, GitSpace/Utilities/HalfSheetManager.swift
- 차단/신고 프로세스가 수행되는 뷰를 구현했습니다.
- #367 
- 차단/신고 프로세스를 수행할 수 있는 뷰 정리(이슈에 작성 완료)
- `BlockView`
- `ReportView`
- `SuggestBlockView`: 신고 후 차단할 지 물어보는 뷰
- `Report.ReportReasonDescription` 생성
- ReportView에서 신고를 설명하기 위해 Enum을 새롭게 추가하였다.
- Report와 연관을 짓고, 휴먼 에러를 줄이기 위해 Enum을 선택하였다.
- `Report.ReportReason`에 `CaseIterable` 프로토콜 추가
- Enum이 가진 모든 값의 컬렉션을 제공할 수 있도록 하는 프로토콜이다.
> iOS 15에는 Sheet의 크기를 설정할 수 없어서 Custom으로 구현하였다.
- `halfSheet`: halfSheet를 사용할 때 View의 수정자로 작성하면 된다.
- View Extension에 구현되어 있다. 
- TargetUserProfileView에서 사용 중이다.
- `HalfSheetManager`: 
- `CustomHostingController`: HostingController에서 UISheetPresentationController 사용
> 차단/신고 뷰를 사용하려면 .halfSheet를 사용하면 된다. 사용법은 .sheet와 같다.
1. 차단/신고 모달이 나타나길 원하는 뷰에 `.halfSheet { .. }` 를 추가한다.
2. `.halfSheet`의 매개변수 `isPresented`, `content`를 채워준다.
* 해당 …
=> [Feat] #367 차단/신고 뷰를 구현했습니다.

GitSpace/Sources/Network/Interface/Blockable.swift
- 주체 사용자(subjectUser)가 객체 사용자(objectUser)를 차단했는지 검증하는 메서드를 구현했습니다.
- #369 
- 주체 사용자(subjectUser)가 객체 사용자(objectUser)를 차단했는지 검증하는 메서드를 구현
- 링크된 이슈에서 메서드에 대한 설명을 보실 수 있습니다.
```swift
/**
verifyBlocked(by: , with: ) 메소드는 subjectUser가 objectUser를 차단했는지 검증하는 함수입니다.
subjectUser가 이미 objectUser를 차단했다면 true를 반환하고,
차단을 하지 않았다면 false를 반환합니다.
- Parameters:
- by subjectUser: UserInfo 타입, 차단을 한 주체
- with objectUser: UserInfo 타입, 차단을 당한 객체
- Returns: - Bool
*/
func verifyBlocked(
by subjectUser: UserInfo,
with objectUser: UserInfo
) -> Bool {
return subjectUser.blockedUserIDs.contains(objectUser.id)
}
```
=> [Feat] 주체 사용자(subjectUser)가 객체 사용자(objectUser)를 차단했는지 검증하는 메서드를 구현했습니다.

GitSpace.xcodeproj/project.pbxproj, GitSpace/Sources/Views/Common/BlockView.swift, GitSpace/Sources/Views/Common/SuggestBlockView.swift
- BlockView, SuggestBlockView의 'Yes' 버튼의 스타일을 변경했습니다.
- #377 
- BlockView의 'Yes' 버튼의 스타일을 .plainText로 변경, isDestructive에 true 전달
- SuggestBlockView의 'Yes' 버튼의 스타일을 .plainText로 변경, isDestructive에 true 전달
| | BlockView | SuggestBlockView |
|:-------:|:-------:|:--------:|
| After | <img width="300" alt="image" src="https://user-images.githubusercontent.com/50159740/234221035-6c9d0e02-17db-4178-a442-7b28c4bee90c.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/50159740/234220921-d3ad3ca7-4661-4d77-a996-6799599411cb.png"> |
| Before | <img width="300" alt="image" src="https://user-images.githubusercontent.com/50159740/234220397-ce31f531-6197-4f67-b9b1-4a22210a63e6.png"> | <img width="300" alt="image" …
=> [Fix] 차단/차단제안 뷰의 텍스트 버튼 디자인을 변경했습니다.

GitSpace/Sources/ViewModels/GitHubAuthManager.swift, GitSpace/Sources/ViewModels/MessageViewModel.swift, GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift, GitSpace/Sources/Views/Chat/ChatRoom/MessageCell.swift
- ChatRoomView에서 상대방 Message Cell을 ContextMenu로 신고할 수 있는 로직을 추가했습니다.
- #373
- 상대방 MessageCell에 ContextMenu 추가
- MessageViewModel에 신고 대상 Message 데이터를 담을 수 있는 reportedMessage 추가
- reportedMessage를 옵저빙해서 신고 sheet를 present 할 수 있는 로직 추가
1. 상대방 MessageCell의 ContextMenu로 report 버튼을 탭하면 해당 Message 객체가 messageViewModel의 reportedMessage에 전달됩니다.
2. ChatRoomView에서는 onChange로 reportedMessage의 변경을 감지합니다.
3. onChange 스코프 내부에서 신고 sheet를 present 하는 로직을 수행합니다.
MessageCell 각각에 ContextMenu를 분리해서 작동하기 위해서는 ChatRoomView가 아닌 MessageCell 내부에서 ContextMenu를 구현해야합니다. 대신 이 방법을 사용할 경우 MessageCell 내부에서 직접 ChatRoomView로 특정 Message 객체를 전달할 방법이 없기 때문에 공통으로 참조하고 있는 MessageViewModel을 활용합니다. 
sheet와 같이 View 전체 영역에서 사용해야 하는 컴포넌트를 MessageCell에서 구현하게되면 Cell 영역 만큼만 sheet가 작동합니다. 그래서 sheet는 ChatRoomView에서 구현해야하고, 동시에 어떤 메세지가 신고의 …
=> [Feat] 채팅방에서 상대방 메세지를 신고할 수 있는 기능을 추가했습니다.

GitSpace/Sources/Models/Report.swift, GitSpace/Sources/Views/Common/ReportView.swift
- ReportReasonDescription 열거형을 삭제하고 신고사유에 대한 설명을 리턴하는 메서드를 구현하였습니다.
- #378 
- ReportReasonDescription 열거형 삭제
- ReportReason 내부에 `getDescription` 메서드 생성
<br>
Report 구조체가 아닌, ReportReason 열거형 내부에 생성한 이유는 다음과 같습니다.
* 각 신고 사유에 대한 설명을 반환하는 함수이므로, ReportReason의 기능에 포함된다고 판단함.
* Report 구조체 내부 메서드로 구현할 경우, ReportReason의 각 케이스에 대한 분기 처리 구현이 어려움.
* 이렇게 구현할 경우 호출시에 `Report().getDescription(-)`으로 해줘야 하며, ReportReason에 대한 각 케이스를 따로 전달해줘야 하는 번거로움이 발생함.
* ReportReason 열거형 내부 메서드로 생성할 경우, 메서드 내부에 self를 사용하여 쉽게 신고 사유별로 분기 처리 가능 
```diff
enum ReportReason: String, Codable, CaseIterable {
case spamming = "Spamming"
case offensive = "Verbal Abuse, Offensive Language"
case sexual = "Sexual Description(Activity)"
case cheating = "Cheating"
case bullying = "Cyberbullying or Harassment"
+   func getDescription() …
```
=> [Fix] ReportReasonDescription 열거형을 메서드로 변경했습니다.

GitSpace.xcodeproj/project.pbxproj, GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift, GitSpace/Sources/Views/Knock/SendKnockView.swift, GitSpace/Utilities/Components/GSTextEditor.swift, GitSpace/Utilities/Constant.swift, GitSpace/Utilities/Modifiers/GSTextEditorLayoutModifier.swift
- 유저의 차단 여부를 검사하여 차단한 / 차단당한 유저에게 채팅 메세지를 전송하지 못하도록 처리했습니다.
- #372 
- GSTextEditor에 isBlocked 프로퍼티 추가
- isBlocked 조건에 따라 TextEditor 속성 분기 처리
- GSTextEditor 분기에서 공통되는 속성자에 대한 Modifier 구현
```swift
if isBlocked {
TextEditor(
text: .constant(const.TEXTEDITOR_BLOCKED_LABEL)
)
.modifier(
GSTextEditorLayoutModifier(
font: font,
color: .gsGray1,
lineSpace: lineSpace,
maxHeight: textEditorHeight,
horizontalInset: const.TEXTEDITOR_INSET_HORIZONTAL,
bottomInset: const.TEXTEDITOR_INSET_BOTTOM
)
)
.disabled(true)
.overlay {
RoundedRectangle(cornerRadius: const.TEXTEDITOR_STROKE_CORNER_RADIUS)
.stroke()
.foregroundColor(.gsGray2)
.background(
Color.gsGray3.opacity(0.7)
)
.cornerRadius(const.TEXTEDITOR_STROKE_CORNER_RADIUS)
}
.onAppear {
setTextEditorStartHeight()
}
} else {
...
}
```
=> [Feat] 차단 여부에 대한 채팅 기능 분기처리를 구현했습니다.

GitSpace/Sources/Views/Common/BlockView.swift, GitSpace/Sources/Views/Common/SuggestBlockView.swift
- 차단/차단제안 뷰의 텍스트 버튼을 새롭게 디자인하여 적용하였습니다.
- #383 
- 차단/차단제안 뷰의 텍스트 버튼을 한번 바꾼 후 팀원들의 피드백을 받아 다시 텍스트 버튼을 Re-design 했습니다.
- 'Yes' 버튼은 빨간색 바탕에 흰색 텍스트로 변경
- 'No' 버튼은 흰색 테두리를 가진 텍스트 버튼으로 변경
|              | BlockView | SuggestBlockView |
|:-------:|:----:|:----:|
| After    |  <img width="300" alt="image" src="https://user-images.githubusercontent.com/50159740/234788908-44fc4be0-341c-4f55-bf9f-d12f46df3469.png">  |  <img width="300" alt="image" src="https://user-images.githubusercontent.com/50159740/234789369-a035b2d5-1a19-4c21-b390-b90f20cc2390.png"> |
| Before | <img width="300" alt="image" src="https://user-images.githubusercontent.com/50159740/234221035-6c9d0e02-17db-4178-a442-7b28c4bee90c.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/50159740/234220921-d3 …
=> [Fix] 차단/차단제안 뷰의 텍스트 버튼을 다시 디자인했습니다.

GitSpace/Sources/Views/Common/BlockView.swift, GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
- TargetUserProfileView에서 유저 차단 기능을 구현하였고, 차단여부에 따라 뷰에 반영할 수 있도록 작업하였습니다.
- #376 
- TargetUserProfileView에 진입시, 현재 GitHub에서 해당 유저 팔로우 여부가 초기화되어 나타나는 현상 수정
- TargetUserProfileViewModel을 ObservedObject에서 StateObject로 변경 
- TargetUserProfileView에 진입시 해당 유저가 Blocked된 유저인지 여부를 판별합니다
- 해당 여부에 따라 뷰 상단에 Blocked 유저인지 표시합니다. 
- BlockView에서는 지난 회의에서 함께 만들어 두었던 `Blockable` 프로토콜을 채택하여, 유저를 block하는 메서드를 사용하였습니다.
- @guguhanogu 님이 block유저를 관리하기 위해 만들어둔 EnvironmentObject를 사용하였습니다.
- UIViewControllerRepresentable로 구현되어 있는 HalfSheetManager를 통해 BlockView를 열어줄 때 에러 발생
- EnvironmentObject 를 가지고 있는 BlockView에서 @guguhanogu 님이 만들어둔 EnvironmentObject가 없다는 내용의 에러 발생 
- 상위뷰인 TargetUserProfileView에서 BlockView가 생성될 때 EnvironmentObject에 추가되도록 .environmentObject를 추가하여 해결
- 기능은 동작하나, 원인 파악중입니다.
|              | 일반 유저 | …
=> [Feat] TargetUserProfileView에서 차단 기능을 구현하고, 차단여부에 따라 뷰에 반영하였습니다.

GitSpace/Sources/ViewModels/MessageViewModel.swift, GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift, GitSpace/Sources/Views/Chat/ChatRoom/MessageCell.swift
- 채팅방에 차단 분기 처리를 위한 검사 로직 연결
- 신고 Sheet 추가
- #388 
- GSTextEditor에 차단 검사 메서드 호출 결과 전달
- 신고 sheet present 바인딩 변수 추가
- onChange에서 감지하기 위한 isReported 변수 추가
- 신고 sheet present 로직 추가
- 신고 sheet View 작성
```swift
.halfSheet(isPresented: $showingReportView) {
ReportView(
isReportViewShowing: $showingReportView,
isSuggestBlockViewShowing: $showingSuggestBlockView
)
}
/* Submit Report */
GSButton.CustomButtonView(
style: .secondary(isDisabled: isReportReasonSelected)
) {
/* report method call */
/* report view dismiss -> suggest block view appear*/
dismiss()
isReportViewShowing.toggle()
isSuggestBlockViewShowing.toggle()
} label: {
Text("Submit Report")
}
```
ReportView에 노크/채팅 메세지 객체를 전달하기 위해 report method call 로직 논의 필요 w. @dahae0320
=> [Feat] 채팅방에 차단 검사와 신고 Sheet를 연결했습니다.

GitSpace/Sources/Views/Common/BlockView.swift, GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
#394 
- 유저 블락 기능 사용시, BlockView에서 블락 버튼을 누른 뒤 블락했다는 사실을 알 수 있도록 TargetUserProfileView에 즉시 반영하였습니다. 
- TargetUserProfileView 및 BlockView에 State, Binding 변수 생성
- Block 버튼을 누르면 연결된 변수를 트리거로 사용하여 뷰에 반영
- 기존 GitHubUser 할당 로직을 private 함수로 변경
- 변수명 변경 
| BlockView 및 TargetUserProfileView | 
|:-------:|
| <img width="300" alt="gif" src="https://user-images.githubusercontent.com/19788294/235986284-e1744c2a-cc6c-4949-9745-4be68f2f55ea.gif">|
=> [Fix] 유저를 블락할 경우, 블락했다는 사실을 알 수 있도록 뷰를 리프레시 합니다. 

GitSpace/InitialView.swift, GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
- #393 
- 기존 깃스페이스 유저 확인 로직이 잘 작동하는지 확인
- GitSpace 유저인지 확인하는 작업이 랜덤하게 작동하는 현상 발생
- RepositoryDetailView에서 TargetUserProfileView 진입시에는 잘 작동하다가, ChatRoomView를 통해 TargetUserProfileView를 진입하면 로직이 작동하지 않음
- GitSpace 유저 검증 로직 자체에는 문제가 없으나, UserStore 클래스의 Published 배열인 users가 초기화 되는 현상으로 파악되었습니다.
- 따라서 InitialView에서 **UserStore 클래스의 인스턴스를 직접 생성하여** .environmentObject() 수정자로 등록하던 코드를 아래와 같이 변경하였습니다.
- **UserStore 클래스의 인스턴스를 StateObject로 선언한 뒤**, .environmentObject() 수정자로 등록하여 Published 배열인 users가 초기화 되지 않도록 변경
- 이제 다양한 뷰에서 접근해도 TargetUserProfileView에서 GitSpace 유저인지 검증하는 로직이 정상 작동합니다.
- GitSpace 유저 검증 로직 수행 후 깃스페이스 유저가 아니거나, 현재 사용자인 경우 차단/신고 메뉴 버튼(Ellipsis)를 제거하였습니다.
- 이미 블락된 유저인 경우, 메뉴에서 block 버튼이 나타나지 않도록 처리하였습니다.
| view | 수정 이전 | 수정 이후 | 
|:-------:|:-------:|:-------:|
| GitSpace 유저 검증 로직 여부 …
=> [Fix] 깃스페이스 유저가 아닌 경우 TargetUserProfileView에서 신고 메뉴 버튼(Ellipsis)가 보이지 않도록 처리하였습니다.

GitSpace/Sources/ViewModels/ChatViewModel.swift, GitSpace/Sources/ViewModels/KnockHistory/KnockViewManager.swift, GitSpace/Sources/Views/Chat/MainChat/MainChatView.swift, GitSpace/Sources/Views/Settings/Account/SetAccountView.swift
- Chat, Knock 등 일부 ViewModel에서는 Firestore 읽기 최적화를 위해 최초 1회에만 Request 하도록 구현되어있습니다.
- 현재 회원 탈퇴 시 로컬 ViewModel에 남아있는 이전 유저의 데이터가 그대로 노출되는 현상이 있어 수정이 필요합니다.
- #405 
- 1회만 Request 하는 기존 ViewModel 로직 파악
- Reset 로직 구현
```swift
private func reset() {
chatViewModel.removeChatList()
knockViewManager.removeKnockList()
}
```
=> [Feat] 회원 탈퇴 시 로컬 데이터를 초기화하는 기능을 추가했습니다.

GitSpace/Sources/Models/UserInfo.swift, GitSpace/Sources/Router/ContentView.swift, GitSpace/Sources/ViewModels/UserViewModel.swift, GitSpace/Sources/Views/Knock/MainKnockBox/EachKnockCell.swift, GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift, GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift, GitSpace/Utilities/Constant.swift
- #391 
- #390 
- NavigationView -> Stack Style 추가
- Chat View Route에서 bound-back 되는 현상 해결
- SkeletonUI가 삭제된 유저를 대상으로 placeholderImage로 나오도록 수정
- Animation이 걸리는 View에 id를 `knock.id`로 새로 할당
| User가 삭제되었을 때, <br> KnockHistoryView |
| :------: |
| ![](https://i.imgur.com/XFfFxFk.png) |
```swift
// SKELETONUI 수정 부분
ZStack {
Color.white
.zIndex(0)
.clipShape(Circle())
// 아래 있는 코드의 뷰가 더 상위에 떠야하므로 zIndex 1
Circle()
.fill(.gray)
.opacity(opacity)
.zIndex(1)
}
.frame(width: 50)
.overlay {
/// 만약 타겟유저가 fetch되고, 그 id 가 "FAILED"가 아닐 경우
/// githubProfileImage를 그린다.
if
let targetUserInfo,
targetUserInfo.id != "FAILED" {
GithubProfileImage(
urlStr: targetUserInfo.avatar_url,
size: 50
)
}
/// 만약 타겟유저가 fetch되고, 그 id 가 FAILED일 경우
/// fetch가 실패했다는 의미로 DefaultProfileImage를 그린다.
else if
let targetUserInfo, …
```
=> Fix/#391, Fix/#390 knock profile image skeleton UI fix

GitSpace/Sources/Views/Settings/AppSettings/SetAppearanceView.swift, GitSpace/Utilities/Components/GSTabBarIcon.swift
- 앱 내에 햅틱 피드백을 추가했습니다.
- #408 
- 앱 내에 햅틱 피드백을 추가했습니다.
- SetAppearanceView
- GSTabBarIcon
```diff
.onTapGesture {
tabBarRouter.currentPage = page
+   UIImpactFeedbackGenerator(style: .rigid).impactOccurred()
}
```
=> [Feat] 앱 내에 햅틱 피드백을 추가했습니다.

GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomView.swift, GitSpace/Sources/Views/Common/ReportView.swift, GitSpace/Sources/Views/Home/RepositoryDetailView.swift, GitSpace/Sources/Views/Knock/MainKnockBox/KnockHistoryView.swift, GitSpace/Sources/Views/Knock/MainKnockBox/ReceivedKnockDetailView.swift, GitSpace/Sources/Views/Knock/SendKnockView.swift, GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
- 신고한 유저가 이미 차단한 유저일 경우, 차단제안뷰(SuggestBlockView)가 나오지 않도록 수정했습니다.
- #396 
<br>
```swift
struct ReportView: View { 
@EnvironmentObject var blockedUsers: BlockedUsers
var targetUser: UserInfo
var isBlocked: Bool {
blockedUsers.blockedUserList.contains(where: { $0.userInfo.id == targetUser.id })
}
...
}
```
* `blockedUser`
* 현재 사용자가 차단한 유저의 목록을 사용하기 위해 BlockedUsers의 전역 객체를 사용합니다.
* `targetUser`
* ReportView에서 차단할 사용자입니다.
* `isBlocked`
* 현재 사용자가 차단한 유저의 목록에서 targetUser(차단한 유저)가 있는지 확인한 결과를 가지고 있습니다.
<br>
- `TargetUserProfileView`
- `ChatRoomVIew`
- `ReceivedKnockDetailView`
- `KnockHistoryView`
```diff
.sheet(isPresented: $isReportViewShowing) {
+ if let targetUser = targetUserInfo {
ReportView(
isReportViewShowing: $isReportViewShowing,
isSuggestBlockViewShowing: $isSuggestBlockViewShowing, …
```
=> [Fix] #396 신고한 유저가 이미 차단한 유저일 경우, 차단제안뷰가 나오지 않도록 수정했습니다.

GitSpace/Sources/ViewModels/TagViewModel.swift, GitSpace/Sources/Views/Home/AddTagSheetView.swift, GitSpace/Sources/Views/Home/RepositoryDetailView.swift, GitSpace/Sources/Views/Home/StarredView.swift
- Repository에 tag를 등록하고 다시 태그추가뷰로 가면 deselect 되어있는 버그를 고쳤습니다.
- #397 
1. Repository에 tag를 등록하고 다시 AddTagSheetView로 가면 방금 등록한 tag가 deselect 되어 있다. (select이 되어야 정상)
2. 그 상태에서 해당 tag를 다시 등록하면 Repository에 같은 tag가 1개 더 들어간다. (DB에는 반영x, view에서 중복으로 표현)
1. RepositoryDetail에서 '+'버튼 눌러 AddTagSheetView로 이동
2. AddTagSheetView에서 특정 Tag를 Selection 후 Done 버튼 탭
3. AddTagSheetView dismiss
4. RepositoryDetail Appear
5. 다시 1번 - 4번 반복하면 RepositoryDetail의 My Tag에 같은 태그가 2번 들어간다.
모든 tag를 보여주는 반복문에서 사용자가 만든 tag들(tagViewModel.tags)과 선택된 tag들(selectedTags)에서 겹치는 tag를 선택된 tag로 보여주고 있습니다.
작업 이전에는 겹치는 tag가 있는지 확인하는 로직에서 tag 객체를 기준으로 비교하고 있었습니다. 그래서 tag를 등록한 직후에는 해당 tag값에 repo 정보가 들어가 있지 않습니다. 
한마디로 " **이름과 id는 같지만 repo 정보가 채워져있지 않아서 같은 tag로 인식하지 못한 것** "이 원인입니다.
단순하게 Firebase에서 tag 정보를 다시 받아올 수 있었지만, (1)request 요청이 …
=> [Fix] Repository에 tag를 등록하고 다시 태그추가뷰로 가면 deselect 되어있는 버그를 고쳤습니다.

GitSpace/Sources/Views/Common/BlockView.swift, GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
- 신고, 차단 로직의 toggle 호출을 정리하였습니다.
- #416 
- 가독성을 높이고 오류 발생을 막기 위해 .toggle() 메서드가 아닌, Bool값을 직접 할당하였습니다.
- 유저에 대한 차단을 해제했음에도 ChatRoom에 진입시 TextField가 막혀있는 문제가 간헐적으로 발생합니다.
- ChatRoom -> View Profile -> TargetUserProfileView -> 차단 -> 다시 ChatRoom 순서대로 이동시 유저를 차단했음에도 아직 TextField가 막혀있지 않는 현상이 발생합니다.
=> [Fix] 신고, 차단 로직의 toggle 호출을 정리합니다

GitSpace.xcodeproj/project.pbxproj, GitSpace/Sources/Models/BlockedUsers.swift, GitSpace/Sources/Network/Interface/Blockable.swift, GitSpace/Sources/Views/Common/BlockView.swift, GitSpace/Sources/Views/Settings/Account/SetAccountView.swift
- BlockedUsers Class의 위치를 변경했습니다.
- 중복 검사 후에 BlockedUserList에 값을 추가하도록 했습니다.
- 로그아웃 / 회원탈퇴 시 BlockedUserList를 비우게 했습니다.
- #412 
- `BlockedUsers.swift` 파일을 추가했습니다.
- `BlockedUsers` Class의 위치를 변경했습니다.
- 전: `Blockable.swift`
- 후: `BlockedUsers.swift`
- `BlockedUsers` Class에 주석을 추가했습니다.
- 현재 차단한 유저를 다시 차단할 수 없지만,
만일을 위해 중복검사를 통해 중복된 값이 추가되지 않도록 합니다.
- **주요 로직**
```swift
//  BlockView.swift
if !blockedUsers.blockedUserList.contains(
where: {
$0.0 == targetUser &&
$0.1 == targetGitHubUser
}) {
blockedUsers.blockedUserList.append((targetUser, targetGitHubUser))
}
```
- **주요 로직**
```diff
//  SetAccountView.swift
//  #72 line 
.alert("Sign out", isPresented: $showingLogoutAlert) {
Button("Sign out", role: .destructive) {
+       blockedUsers.blockedUserList.removeAll()
gitHubAuthManager.signOut() …
```
=> [Chore] BlockedUsers Class의 위치를 변경하고, BlockedUserList의 중복검사, 로그아웃/회원탈퇴 시 목록 비우기를 진행했습니다.

GitSpace/Sources/Router/ContentView.swift, GitSpace/Sources/Views/Home/ContributorListView.swift, GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
- #422 
- GitSpace 유저 검증 로직을 수정하였습니다.
- 신고와 차단 기능이 추가되면서, TargetUserProfileView에서 BlockView 및 ReportView에 UserInfo 타입의 구조체를 주입하고 있습니다. (신고 및 차단은 GitSpace 유저간의 활동이기 때문)
- **TargetUserProfileView에서 사용되는 GitHubUser 타입의 구조체**와는 달리, **BlockView 및 ReportView에서는 UserInfo 타입의 구조체**가 필요합니다. 
- 따라서 TargetUserProfileView에 진입시, GitHubUser의 id를 사용하여 Firestore db에서 쿼리를 실행하여 해당 github id를 가진 유저가 있다면 **UserInfo** 타입의 구조체를 리턴하고, 없다면 nil을 리턴하는 `.requestUserInfoWithGitHubID(githubID: )` 메서드를 사용합니다.
- 즉, 해당 메서드의 리턴값이 nil이라면, GitSpace를 사용하는 모든 유저를 저장하고 있는 Firestore의 UserInfo Collection에 해당 GitHub ID를 가진 유저가 없다는 뜻이고, 이는 즉 GitSpace 유저가 아니라는 의미를 내포합니다.
- 기존 검증 로직이었던 ContentView에서 `UserStore.requestUsers()`메서드를 실행하여 모든 GitSpace 유저를 일일히 배열에 저장한 뒤 비교하는 방법을 사용하지 않고도 GitSpace 유저임을 검증할 수 있습니다.
- 이에 따라 기존 GitSpace 유저 …
=> [Fix] GitSpace 유저 검증 로직을 수정하였습니다.

GitSpace/Sources/Router/KnockCommunicationRouter.swift, GitSpace/Sources/Views/Common/TopperProfileView.swift, GitSpace/Sources/Views/Home/ContributorListView.swift, GitSpace/Sources/Views/Profile/TargetUserProfileView.swift
- `View Profile` → `Chat/Knock View` → `View Profile`의 무한 라우팅을 해결했습니다.
- #424 
> 무한 라우팅을 해결하기 위해서는
> 반복적으로 Push 되는 뷰가 있을 경우 `NavigationLink` 등을 통한 뷰 이동을 끊고 이전 뷰로 돌아가야 합니다.
> **GitSpace**에서 무한 라우팅이 발생하는 시나리오는 다음과 같습니다.
1. `Chat View` → `View Profile` 링크 → `Knock`링크
2. `Received Knock View` → `View Profile` 링크 → `Knock` 링크
3. `Send Knock View` → `View Profile` 링크 → `Knock` 링크
위의 시나리오에서 공통적으로 `TopperProfileView`의 `View Profile` 링크를 통해
`TargetUserProfileView`로 이동하면서 무한 라우팅이 시작됩니다.
`TopperProfileView'의 'View Profile` 링크로 TargetUser의 프로필로 이동 후,
해당 유저 프로필의 `Knock` 링크를 눌렀을 때 이전 뷰로 돌아가도록 해야 합니다.
- **[참고]** [**Coordinator Pattern in SwiftUI**](https://labs.brandi.co.kr//2022/12/12/leehs81.html)
- Coordinator Pattern은 화면전환에 관련된 코드를 Coordinator 라고 하는 별도의 모델로 책임을 분리하는 디자인 패턴 중 하나입니다.
아키텍처로 고도화 할 경우, …
=> [Fix] View Profile → Chat/Knock View → View Profile의 무한 라우팅을 해결했습니다.

GitSpace/Sources/Router/ContentView.swift, GitSpace/Sources/ViewModels/ChatViewModel.swift, GitSpace/Sources/ViewModels/UserViewModel.swift
- #426 
<br><br>
차단 기능이 추가되면서 차단 액션 후 `User`의 차단 목록 업데이트가 필요합니다.
Firestore DB에는 업데이트가 반영되지만, 로컬 `User` 데이터에도 반영이 필요한데, 차단 기능이 `Blockable` 프로토콜에 의존하는 구조로 되어있습니다.
프로토콜 내부에서는 `EnvironmentObject` 사용이 불가해서 앱 전반에서 사용하는 `UserViewModel`에 접근할 수 없기 때문에 차단 기능을 사용하는 모든 View에서 `UserViewModel`을 의존하고 직접 `User` Request 호출까지 별도로 해야하는 상황입니다.
이를 해결하기 위해 Firestore DB의 `User`가 업데이트 될 때, 이를 감지하여 로직을 수행할 수 있는 `Listener`를 구현합니다.
<br><br>
- `UserViewModel`의 Extension으로 `addListener`와 `removeListener` 메서드가 추가되었습니다.
- `ContentView` (로그인 직후 첫 진입 뷰) 진입 시 `addListener`, 탈출 시 `removeListener`를 호출하는 코드가 추가되었습니다.
<br><br>
```swift
// MARK: - Listener
extension UserStore {
func addListener() {
listener = db
.collection(const.COLLECTION_USER_INFO)
.document(Utility.loginUserID)
.addSnapshotListener { snapshot, error in …
```
=> [Feat] User Listener를 구현했습니다.

GitSpace/Sources/Models/Chat.swift, GitSpace/Sources/Models/Message.swift, GitSpace/Sources/ViewModels/ChatViewModel.swift, GitSpace/Sources/ViewModels/MessageViewModel.swift, GitSpace/Sources/Views/Chat/ChatRoom/ChatRoomKnockSection.swift
- #442 
- #447 
- 사용자의 개인정보 및 사생활 보호를 위해 Chat, Message 등 채팅 기능 사용 전반에서 생성되는 텍스트 컨텐츠에 대한 암호화를 적용했습니다.
- Chat과 Message 객체에 인코딩 / 디코딩 처리된 객체 생성 메서드 추가
- Request, Add, Update 등 CRUD 시점에 인코딩 or 디코딩 처리 로직 추가
- 기존 객체를 받아서 인코딩 / 디코딩 처리된 객체를 반환하는 메서드를 추가했습니다.
- 기존 Request, Add 로직에서 Data 자체를 아규먼트로 전달하는 로직을 그대로 유지하기 위해 구현되었습니다.
```swift
static func encodedChat(with chat: Chat) -> Chat {
var encodedChat: Chat = chat
encodedChat.knockContent = chat.knockContent.asBase64 ?? ""
encodedChat.lastContent = chat.lastContent.asBase64 ?? ""
return encodedChat
}
static func decodedChat(with chat: Chat) -> Chat {
var decodedChat: Chat = chat
decodedChat.knockContent = chat.knockContent.decodedBase64String ?? ""
decodedChat.lastContent = chat.lastContent.decodedBase64String ?? ""
return decodedChat
}
static func …
```
=> [Feat] Chat / Message에 Base64 암호화를 적용했습니다.

GitSpace.xcodeproj/project.pbxproj, GitSpace/InitialView.swift, GitSpace/Sources/Network/APIModels/AppInfo.swift, GitSpace/Sources/Network/Services/AppStoreUpdateChecker.swift
- #451 
<br>
- iTunes API Response를 담을 AppInfo 객체를 추가했습니다.
- 앱 버전 체크 기능을 담당하는 AppStoreUpdateChecker 클래스를 추가했습니다.
- 클라이언트 버전과 릴리즈 버전을 비교하는 isNewVersionAvailable 메서드를 추가했습니다.
- App 시작 시점에 버전을 체크해서 강제 업데이트를 유도하는 로직을 추가했습니다.
- AppInfo 모델은 iTunes API의 lookup 정보에 대한 Reponse 타입입니다.
```swift
struct AppInfo: Codable {
let resultCount: Int
let results: [AppInfoResult]
}
struct AppInfoResult: Codable {
let version: String
}
```
- AppStoreUpdateChecker 클래스는 iTunes API 통신, 앱 번들 버전과 릴리즈 버전의 비교 기능 담당합니다.
```swift
enum AppStoreUpdateCheckerError: Error {
case invalidInfoDictionary
case invalidBundleID
case invalidCurrentVersionNumber
case invalidItunesURL
case invalidResponse
case failToDecoding
case unexpectedStatusCode
case unknown
case emptyResponse
}
final class AppStoreUpdateChecker {
static func …
```
=> [Feat] 앱 버전 체크 및 강제 업데이트 로직을 구현했습니다.
